# Generated by Django 5.2.13 on 2026-05-05 15:14

import uuid
from django.db import migrations


def seed_plans(apps, schema_editor):
    Plan = apps.get_model('subscriptions', 'Plan')
    
    # 1. Free Plan
    Plan.objects.get_or_create(
        name='free',
        defaults={
            'display_name': 'Free Plan',
            'max_predictions_per_month': 5,
            'max_audio_duration_seconds': 60,
            'max_upload_size_mb': 20,
            'show_per_model_breakdown': False,
            'price_monthly': 0.00,
            'is_active': True,
        }
    )
    
    # 2. Analyst Plan
    Plan.objects.get_or_create(
        name='analyst',
        defaults={
            'display_name': 'Analyst Plan',
            'max_predictions_per_month': 500,
            'max_audio_duration_seconds': 300,
            'max_upload_size_mb': 20,
            'show_per_model_breakdown': True,
            'price_monthly': 29.99,
            'is_active': True,
        }
    )
    
    # 3. Corporate Plan
    Plan.objects.get_or_create(
        name='corporate',
        defaults={
            'display_name': 'Corporate Plan',
            'max_predictions_per_month': -1, # Unlimited
            'max_audio_duration_seconds': 600,
            'max_upload_size_mb': 50,
            'show_per_model_breakdown': True,
            'price_monthly': 99.99,
            'is_active': True,
        }
    )

def remove_plans(apps, schema_editor):
    Plan = apps.get_model('subscriptions', 'Plan')
    Plan.objects.filter(name__in=['free', 'analyst', 'corporate']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_plans, remove_plans),
    ]
