# Generated by Django 5.2.13 on 2026-04-24 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedAudio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('file_size_bytes', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_audios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_audio',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['uploaded_at'], name='uploaded_au_uploade_88bf34_idx')],
            },
        ),
    ]
